# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import uber_proto_pb2 as uber__proto__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in uber_proto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolicitarViajeStub(object):
    """Servicio 1

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InfoAuto = channel.unary_unary(
                '/uam.SolicitarViaje/InfoAuto',
                request_serializer=uber__proto__pb2.Posicion.SerializeToString,
                response_deserializer=uber__proto__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.TerminarViaje = channel.unary_unary(
                '/uam.SolicitarViaje/TerminarViaje',
                request_serializer=uber__proto__pb2.TerminarViajeRequest.SerializeToString,
                response_deserializer=uber__proto__pb2.TerminarViajeResponse.FromString,
                _registered_method=True)
        self.EstadoServicio = channel.unary_unary(
                '/uam.SolicitarViaje/EstadoServicio',
                request_serializer=uber__proto__pb2.Empty.SerializeToString,
                response_deserializer=uber__proto__pb2.EstadoServicioResponse.FromString,
                _registered_method=True)
        self.SayHello = channel.unary_unary(
                '/uam.SolicitarViaje/SayHello',
                request_serializer=uber__proto__pb2.HelloRequest.SerializeToString,
                response_deserializer=uber__proto__pb2.HelloReply.FromString,
                _registered_method=True)


class SolicitarViajeServicer(object):
    """Servicio 1

    """

    def InfoAuto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminarViaje(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstadoServicio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolicitarViajeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InfoAuto': grpc.unary_unary_rpc_method_handler(
                    servicer.InfoAuto,
                    request_deserializer=uber__proto__pb2.Posicion.FromString,
                    response_serializer=uber__proto__pb2.InfoResponse.SerializeToString,
            ),
            'TerminarViaje': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminarViaje,
                    request_deserializer=uber__proto__pb2.TerminarViajeRequest.FromString,
                    response_serializer=uber__proto__pb2.TerminarViajeResponse.SerializeToString,
            ),
            'EstadoServicio': grpc.unary_unary_rpc_method_handler(
                    servicer.EstadoServicio,
                    request_deserializer=uber__proto__pb2.Empty.FromString,
                    response_serializer=uber__proto__pb2.EstadoServicioResponse.SerializeToString,
            ),
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=uber__proto__pb2.HelloRequest.FromString,
                    response_serializer=uber__proto__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uam.SolicitarViaje', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uam.SolicitarViaje', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolicitarViaje(object):
    """Servicio 1

    """

    @staticmethod
    def InfoAuto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uam.SolicitarViaje/InfoAuto',
            uber__proto__pb2.Posicion.SerializeToString,
            uber__proto__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminarViaje(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uam.SolicitarViaje/TerminarViaje',
            uber__proto__pb2.TerminarViajeRequest.SerializeToString,
            uber__proto__pb2.TerminarViajeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstadoServicio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uam.SolicitarViaje/EstadoServicio',
            uber__proto__pb2.Empty.SerializeToString,
            uber__proto__pb2.EstadoServicioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uam.SolicitarViaje/SayHello',
            uber__proto__pb2.HelloRequest.SerializeToString,
            uber__proto__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
