# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uber_proto.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'uber_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10uber_proto.proto\" \n\x08Posicion\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"p\n\x0cInfoResponse\x12\x12\n\ndisponible\x18\x01 \x01(\x08\x12\x1e\n\x0b\x63oordenadas\x18\x02 \x01(\x0b\x32\t.Posicion\x12\x0c\n\x04uber\x18\x03 \x01(\t\x12\x0e\n\x06tarifa\x18\x04 \x01(\x05\x12\x0e\n\x06placas\x18\x05 \x01(\t\"^\n\x14TerminarViajeRequest\x12!\n\x0eposicion_final\x18\x01 \x01(\x0b\x32\t.Posicion\x12\x0e\n\x06placas\x18\x02 \x01(\t\x12\x13\n\x0b\x63osto_viaje\x18\x03 \x01(\x05\"&\n\x15TerminarViajeResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\"a\n\x16\x45stadoServicioResponse\x12\x19\n\x11viajes_realizados\x18\x01 \x01(\x05\x12\x14\n\x0c\x61utos_libres\x18\x02 \x01(\x05\x12\x16\n\x0eganancia_total\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2\xa9\x01\n\x0eSolicitarViaje\x12$\n\x08InfoAuto\x12\t.Posicion\x1a\r.InfoResponse\x12>\n\rTerminarViaje\x12\x15.TerminarViajeRequest\x1a\x16.TerminarViajeResponse\x12\x31\n\x0e\x45stadoServicio\x12\x06.Empty\x1a\x17.EstadoServicioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSICION']._serialized_start=20
  _globals['_POSICION']._serialized_end=52
  _globals['_INFORESPONSE']._serialized_start=54
  _globals['_INFORESPONSE']._serialized_end=166
  _globals['_TERMINARVIAJEREQUEST']._serialized_start=168
  _globals['_TERMINARVIAJEREQUEST']._serialized_end=262
  _globals['_TERMINARVIAJERESPONSE']._serialized_start=264
  _globals['_TERMINARVIAJERESPONSE']._serialized_end=302
  _globals['_ESTADOSERVICIORESPONSE']._serialized_start=304
  _globals['_ESTADOSERVICIORESPONSE']._serialized_end=401
  _globals['_EMPTY']._serialized_start=403
  _globals['_EMPTY']._serialized_end=410
  _globals['_SOLICITARVIAJE']._serialized_start=413
  _globals['_SOLICITARVIAJE']._serialized_end=582
# @@protoc_insertion_point(module_scope)
